-- ==============================================================================
-- SCHEMA POSTGRESQL PARA SUPABASE - POS BODEGUITAS (MULTI-TIENDA)
-- Puedes copiar y pegar este script en el SQL Editor de tu Dashboard de Supabase.
-- ==============================================================================

-- 1. Habilitar extensión UUID si se requiere
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLA: productos
CREATE TABLE IF NOT EXISTS public.productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bodega_id TEXT NOT NULL, -- o BIGINT si usas números
    cod_ean TEXT,
    descripcion TEXT NOT NULL,
    precio_costo NUMERIC(10, 2) DEFAULT 0.00,
    precio_venta NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    categoria TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABLA: clientes
CREATE TABLE IF NOT EXISTS public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bodega_id TEXT NOT NULL,
    dni TEXT NOT NULL,
    nombre_completo TEXT NOT NULL,
    saldo_actual NUMERIC(10, 2) DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT clientes_bodega_dni_unique UNIQUE (bodega_id, dni)
);

-- 4. TABLA: turnos_caja
CREATE TABLE IF NOT EXISTS public.turnos_caja (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bodega_id TEXT NOT NULL,
    cajero_id TEXT NOT NULL,
    fecha_apertura TIMESTAMPTZ DEFAULT NOW(),
    fecha_cierre TIMESTAMPTZ,
    monto_inicial NUMERIC(10, 2) DEFAULT 0.00,
    estado TEXT DEFAULT 'ABIERTO', -- 'ABIERTO' | 'CERRADO'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABLA: ventas
CREATE TABLE IF NOT EXISTS public.ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bodega_id TEXT NOT NULL,
    turno_caja_id BIGINT REFERENCES public.turnos_caja(id) ON DELETE SET NULL,
    cajero_id TEXT NOT NULL,
    cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE SET NULL,
    nro_boleta TEXT NOT NULL,
    medio_pago TEXT NOT NULL DEFAULT 'EFECTIVO',
    total_venta NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABLA: ventas_detalle
CREATE TABLE IF NOT EXISTS public.ventas_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT REFERENCES public.ventas(id) ON DELETE CASCADE,
    producto_id BIGINT REFERENCES public.productos(id) ON DELETE SET NULL,
    cantidad NUMERIC(10, 2) NOT NULL DEFAULT 1,
    precio_unitario NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- POLÍTICAS RLS (Row Level Security) - Permitir lectura y escritura con clave ANON
-- ==============================================================================
ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.turnos_caja ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ventas_detalle ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir todo a anon en productos" ON public.productos FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo a anon en clientes" ON public.clientes FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo a anon en turnos_caja" ON public.turnos_caja FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo a anon en ventas" ON public.ventas FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo a anon en ventas_detalle" ON public.ventas_detalle FOR ALL TO anon USING (true) WITH CHECK (true);

-- ==============================================================================
-- DATOS SEMILLA INICIALES (DEMO)
-- ==============================================================================
INSERT INTO public.productos (bodega_id, cod_ean, descripcion, precio_costo, precio_venta, categoria) VALUES
('BOD-01', '775012300001', 'Leche Gloria Entera 400g (Azul)', 3.50, 4.20, 'Lácteos'),
('BOD-01', '775012300002', 'Arroz Extra Costeño 1kg', 4.10, 5.00, 'Abarrotes'),
('BOD-01', '775012300003', 'Aceite Vegetal Primor Clásico 900ml', 7.80, 9.50, 'Abarrotes'),
('BOD-01', '775012300004', 'Gaseosa Inca Kola 500ml', 2.20, 3.00, 'Bebidas'),
('BOD-01', '775012300005', 'Gaseosa Coca Cola 500ml', 2.80, 3.50, 'Bebidas'),
('BOD-01', '775012300006', 'Galletas Margarita Field x 6', 2.50, 3.20, 'Golosinas')
ON CONFLICT DO NOTHING;

INSERT INTO public.clientes (bodega_id, dni, nombre_completo, saldo_actual) VALUES
('BOD-01', '99999999', 'CLIENTE VARIOS / GENERAL', 0.00)
ON CONFLICT DO NOTHING;

-- ==============================================================================
-- EXTENSIÓN DE ESQUEMA: INVENTARIO AVANZADO, CRÉDITOS, COMPRAS Y OPERACIONES DE CAJA
-- Bloque incremental y seguro de re-ejecutar sobre una base ya creada con lo anterior.
-- ==============================================================================

-- Productos: SKU y Unidad de Medida (UND / KG) para soporte de balanza
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS sku TEXT;
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS unidad_medida TEXT NOT NULL DEFAULT 'UND';

-- Clientes: datos de contacto y límite de crédito individual
ALTER TABLE public.clientes ADD COLUMN IF NOT EXISTS telefono TEXT;
ALTER TABLE public.clientes ADD COLUMN IF NOT EXISTS correo TEXT;
ALTER TABLE public.clientes ADD COLUMN IF NOT EXISTS limite_credito NUMERIC(10, 2) NOT NULL DEFAULT 200.00;

-- Ventas: anulación (soft-delete, conserva historial) y medio de pago mixto
ALTER TABLE public.ventas ADD COLUMN IF NOT EXISTS anulada BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.ventas ADD COLUMN IF NOT EXISTS motivo_anulacion TEXT;
ALTER TABLE public.ventas ADD COLUMN IF NOT EXISTS monto_efectivo NUMERIC(10, 2) DEFAULT 0.00;
ALTER TABLE public.ventas ADD COLUMN IF NOT EXISTS monto_otro NUMERIC(10, 2) DEFAULT 0.00;

-- Ventas Detalle: cantidad con decimales para productos a granel (ej. 0.350 KG)
ALTER TABLE public.ventas_detalle ALTER COLUMN cantidad TYPE NUMERIC(10, 3);

-- Turnos de Caja: arqueo ciego (esperado vs contado)
ALTER TABLE public.turnos_caja ADD COLUMN IF NOT EXISTS monto_final_real NUMERIC(10, 2);
ALTER TABLE public.turnos_caja ADD COLUMN IF NOT EXISTS ventas_sistema NUMERIC(10, 2) DEFAULT 0.00;
ALTER TABLE public.turnos_caja ADD COLUMN IF NOT EXISTS diferencia NUMERIC(10, 2);

-- TABLA: compras (cabecera de entrada de mercadería / abastecimiento)
CREATE TABLE IF NOT EXISTS public.compras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bodega_id TEXT NOT NULL,
    cajero_id TEXT,
    proveedor_nombre TEXT,
    proveedor_ruc TEXT,
    nro_comprobante TEXT,
    total_compra NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    fecha TIMESTAMPTZ DEFAULT NOW()
);

-- TABLA: compras_detalle
CREATE TABLE IF NOT EXISTS public.compras_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id BIGINT REFERENCES public.compras(id) ON DELETE CASCADE,
    producto_id BIGINT REFERENCES public.productos(id) ON DELETE SET NULL,
    cantidad NUMERIC(10, 3) NOT NULL DEFAULT 1,
    costo_unitario NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABLA: pagos_credito (abonos / cancelaciones de deuda)
CREATE TABLE IF NOT EXISTS public.pagos_credito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bodega_id TEXT NOT NULL,
    cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE CASCADE,
    cajero_id TEXT,
    monto_pagado NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    saldo_anterior NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    saldo_restante NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    medio_pago TEXT NOT NULL DEFAULT 'EFECTIVO',
    fecha TIMESTAMPTZ DEFAULT NOW()
);

-- TABLA: ventas_espera (ventas "aparcadas" en espera de recuperación)
CREATE TABLE IF NOT EXISTS public.ventas_espera (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bodega_id TEXT NOT NULL,
    cajero_id TEXT NOT NULL,
    cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE SET NULL,
    nombre_referencia TEXT,
    items JSONB NOT NULL,
    total NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS para las tablas nuevas
ALTER TABLE public.compras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compras_detalle ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pagos_credito ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ventas_espera ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir todo a anon en compras" ON public.compras;
CREATE POLICY "Permitir todo a anon en compras" ON public.compras FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir todo a anon en compras_detalle" ON public.compras_detalle;
CREATE POLICY "Permitir todo a anon en compras_detalle" ON public.compras_detalle FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir todo a anon en pagos_credito" ON public.pagos_credito;
CREATE POLICY "Permitir todo a anon en pagos_credito" ON public.pagos_credito FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir todo a anon en ventas_espera" ON public.ventas_espera;
CREATE POLICY "Permitir todo a anon en ventas_espera" ON public.ventas_espera FOR ALL TO anon USING (true) WITH CHECK (true);
